version: 2

jobs:

  build:
    docker:
      - image: circleci/php:7.2-stretch
    steps:
      - run:
          name: Git Config
          command: |
            git config --global user.email "${GITHUB_USER_EMAIL}"
            git config --global user.name "${GITHUB_USER_NAME}"
      - checkout
      - run:
          name: Build index page
          command: php -f ./build.php
      - run:
          name: Commit changes
          command: |
            changes=$(git status --short ./docs/index.html);
            if [ -z "$changes" ]; then
              git commit ./docs/index.html -m "Build ${CIRCLE_BUILD_NUM}"
              git push origin ${CIRCLE_BRANCH}
            fi